apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../dsci-metrics/base
  - ../../../cluster-observability-operator/operator/overlays/stable-1.4
  - ../../../opentelemetry/operator/overlays/stable
  - ../../../tempo/operator/overlays/stable
