apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-viewer
  namespace: rhoai-demo-grafana
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-viewer-demo-users
  namespace: rhoai-demo-grafana
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: rhoai-demo-admins
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: rhoai-demo-users
