apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: rhoai-demo-grafana
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
