---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiq-postgres-data
  namespace: research-agents
  labels:
    project: aiq
    app: aiq-postgres
    component: postgres
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
