---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: aiq-frontend
  namespace: research-agents
  labels:
    project: aiq
    app: aiq-frontend
    component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  to:
    kind: Service
    name: aiq-frontend
    weight: 100
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
