---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiq-backend
  namespace: research-agents
  labels:
    project: aiq
    app: aiq-backend
    component: backend
  annotations:
    argocd.argoproj.io/sync-wave: '5'
