apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - subscription.yaml
  - authorino-operator-subscription.yaml
  - limitador-operator-subscription.yaml
  - dns-operator-subscription.yaml
  - approve-installplan.yaml
