apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - odf-mcg/operator/base
  - odf-mcg/instance/base
  - rhoai/operator/base
  - rhoai/instance/overlays/demo
  - model-registry/instance/base
