apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  # Stage 110
  - ../../components/dashboard
  - ../../components/workbenches
  - ../../components/modelregistry
  # Stage 120
  - ../../components/kueue-unmanaged
  # Stage 210
  - ../../components/kserve
  # Stage 220
  - ../../components/maas
