apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana
  namespace: rhoai-demo-grafana
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/component: monitoring
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
