apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
spec:
  channel: stable
  config:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 750m
        memory: 1Gi
  installPlanApproval: Manual
  startingCSV: cluster-observability-operator.v1.4.0
