apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/openshift-monitoring-datasource
  - ../../components/model-serving-dashboards
  - ../../components/console-link
  - ../../components/dashboard-tile
