apiVersion: v1
kind: Service
metadata:
  name: model-registry-db
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  selector:
    app: model-registry-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
