apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: demo-standard-access
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  modelRefs:
    - name: nemotron-nano-30b-hosted
      namespace: models-as-a-service
    - name: nemotron-mini-4b-hosted
      namespace: models-as-a-service
    - name: nemotron-nano-30b
      namespace: demo-sandbox
    - name: nemotron-mini-4b
      namespace: demo-sandbox
  subjects:
    groups:
      - name: system:authenticated
    users: []
