apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
  labels:
    app.kubernetes.io/part-of: rhoai3-nvidia-demo
    app.kubernetes.io/name: opentelemetry-product
    app.kubernetes.io/component: observability
    demo.rhoai.io/stage: "110"
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/display-name: "Red Hat build of OpenTelemetry"
    argocd.argoproj.io/sync-wave: "-1"
